# Generated by Django 6.0.6 on 2026-09-02 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_monthly_fee_alter_enrollment_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.FileField(blank=True, help_text='Upload a JPG, PNG, or WebP profile photo.', upload_to='staff_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
